# Generated by Django 4.0.4 on 2022-06-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='artists',
            new_name='artist',
        ),
    ]
