# Generated by Django 4.0.4 on 2022-06-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0002_rename_artists_record_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='label',
            field=models.ManyToManyField(to='discobase.label'),
        ),
    ]
