# Generated by Django 4.0.4 on 2022-06-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0003_record_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='year',
            field=models.SmallIntegerField(default=2022),
        ),
    ]
