# Generated by Django 4.0.4 on 2022-06-11 11:39

import discobase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0008_trxcredit_remove_credittrx_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rating',
            field=models.SmallIntegerField(default=None, null=True, validators=[discobase.models.validate_rating_value]),
        ),
    ]
