# Generated by Django 4.0.4 on 2022-06-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0009_alter_record_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='ZZ', max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
