# Generated by Django 4.0.4 on 2022-06-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0011_alter_trxcredit_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.SmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('year', models.SmallIntegerField()),
                ('record_format', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(max_length=50)),
                ('artists', models.CharField(max_length=255)),
                ('labels', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.SmallIntegerField(null=True)),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
