# Generated by Django 4.0.4 on 2022-06-18 13:25

import discobase.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0013_alter_trxcredit_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='is_active',
        ),
        migrations.AddField(
            model_name='record',
            name='favourite_song',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='discobase.genre'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rating',
            field=models.SmallIntegerField(default=0, validators=[discobase.models.validate_rating_value]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_format',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='discobase.recordformat'),
        ),
    ]
