# Generated by Django 4.0.4 on 2022-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0014_remove_record_is_active_record_favourite_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cover',
            field=models.ImageField(default='_placeholder.png', upload_to='covers/'),
        ),
    ]
