# Generated by Django 4.0.4 on 2022-06-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0015_record_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='cover',
            field=models.ImageField(default='covers/_placeholder.png', upload_to='covers/'),
        ),
    ]
