# Generated by Django 4.0.4 on 2022-07-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0016_alter_record_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='cover',
            new_name='cover_image',
        ),
        migrations.RemoveField(
            model_name='record',
            name='favourite_song',
        ),
        migrations.AddField(
            model_name='record',
            name='discogs_id',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('is_favourite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='discobase.record')),
            ],
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('record', 'title'), name='song_unique'),
        ),
    ]
