# Generated by Django 4.0.4 on 2022-08-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0018_alter_song_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxcredit',
            name='record_string',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
