# Generated by Django 4.0.4 on 2022-08-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0019_trxcredit_record_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxcredit',
            name='record_string',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
