# Generated by Django 4.0.4 on 2022-10-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discobase', '0020_alter_trxcredit_record_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='discogs_id',
            field=models.IntegerField(default=-1),
        ),
    ]
